openapi: 3.0.0
info:
  version: 0.0-oas3
  title: mushroomClassifier 
  description: An application to identify mushrooms by appearence as edible or nonedible.
  termsOfService: 'http://swagger.io/terms/'
  contact: 
    name: Cloudmesh REST Service Example
  license:
    name: Apache

paths:
  /permissions:
    get:
      tags:
        - Permissions
      summary: ask for permissions to store data
      operationId: permissions.ask
      responses:
        '200':
          description: 'Permissions required: <MORE ON PERMISSIONS>'

  /classify/<bruises>/<odor>/<gillSize>:
    get:
      tags:
        - Permissions
      summary: ask for permissions to store data
      operationId: predict.classify
      responses:
        '200':
          description: 'Permissions required: <MORE ON PERMISSIONS>'

  /predict/<dat>:
    post:
      tags:
        - Upload
      summary: Upload appearance info 
      operationId: comm.upload_form
      parameters:
        - name: data 
          in: query
          description: filename to be uploaded 
          required: true 
          schema:
            type: string #want this to be a csv formatted string could also be a file -- not sure how yet 
      responses:
        '405':
          description: Invalid input
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
    get:
      tags:
        - Download
      summary: Download the fillout form 
      operationId: comm.download 
      responses:
        '405':
          description: Invalid input

  /upload/<photo>:
    post:
      tags:
        - Upload 
      summary: Upload a picture
      operationId: comm.upload_photo
      parameters:
        - name: photo
          in: query
          description: photo of the given input
          required: true
          schema:
            type: string #not sure how to lable this for now... want it to be an image upload 

      responses:
        '403':
          description: File too large, compress
        '405':
          description: Invalid input
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary

servers:
  - url: 'http://localhost:8080/mc'


